<!DOCTYPE person [
  <!ELEMENT person (name, address, phone+)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
]>
<person>
  <name>person2</name>
  <address>mumbai</address>
  <phone>+9112432432</phone>
  <phone>+9112432432</phone>
</person>